In [ ]:
# Manipulação de Dados

import pandas as pd

In [ ]:
# DataFrames - df
# df_exemplo ou df_vendas

# importando um arquivo csv separado por vírgula

df = pd.read_csv('/content/drive/MyDrive/!Data Python 2603/base_vendas.csv')
print(df)

In [ ]:
# Display - Mostra as 5 primeiras linhas e as 5 últimas linhas
# caso o arquivo for pequeno, ele exibe todas

display(df)

In [ ]:
# Na primeira vez que abrimos, ele entende que está separado por vírgula
# Para escolhermos o separador, podemos usar:
# delimiter='separador'   ou  sep='separador'

# importando um arquivo csv separado por ponto e vírgula

df = pd.read_csv('/content/drive/MyDrive/!Data Python 2603/base_vendas_ponto_virgula.csv', sep=';')
display(df)

In [25]:
# importando um arquivo csv separado por tabulação

df = pd.read_csv('/content/drive/MyDrive/!Data Python 2603/base_vendas_tab.tsv', sep='\t')
display(df)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,123456111,José Maria,Vendedor,CL001,Loja Matriz,10017,Cama Box,Casa,"1189,9","1899,5",3,NaN,05/03/2020 12:58,11/03/2020 10:27
96,123456111,José Maria,Vendedor,CL001,Loja Matriz,10005,Notebook,Eletrônicos,"2299,9",3199,3,NaN,07/08/2020 13:11,07/08/2020 14:53
97,123456111,José Maria,Vendedor,CL001,Loja Matriz,10020,Impressora,Eletrônicos,"329,9","674,1",3,NaN,29/09/2019 09:05,29/09/2019 12:15
98,123456111,José Maria,Vendedor,CL001,Loja Matriz,10012,Processador de alimentos,Cozinha,110,"189,9",3,NaN,30/09/2019 16:49,01/10/2019 14:55
99,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",3,NaN,08/11/2020 14:32,09/11/2020 09:48

In [26]:
# importando um arquivo h5

df = pd.read_hdf('/content/drive/MyDrive/!Data Python 2603/base_vendas.h5')
display(df)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,123456111,José Maria,Vendedor,CL001,Loja Matriz,10017,Cama Box,Casa,"1189,9","1899,5",3,NaN,05/03/2020 12:58,11/03/2020 10:27
96,123456111,José Maria,Vendedor,CL001,Loja Matriz,10005,Notebook,Eletrônicos,"2299,9",3199,3,NaN,07/08/2020 13:11,07/08/2020 14:53
97,123456111,José Maria,Vendedor,CL001,Loja Matriz,10020,Impressora,Eletrônicos,"329,9","674,1",3,NaN,29/09/2019 09:05,29/09/2019 12:15
98,123456111,José Maria,Vendedor,CL001,Loja Matriz,10012,Processador de alimentos,Cozinha,110,"189,9",3,NaN,30/09/2019 16:49,01/10/2019 14:55
99,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",3,NaN,08/11/2020 14:32,09/11/2020 09:48

In [27]:
# importando um arquivo json

df = pd.read_json('/content/drive/MyDrive/!Data Python 2603/base_vendas.json')
display(df)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,None,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,None,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,None,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,None,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,"88,9","189,9",3,None,04/11/2019 15:40,05/11/2019 10:40
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,"59,9","142,4",3,None,24/06/2019 09:04,24/06/2019 10:50
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,"49,9","95,9",3,None,08/08/2020 14:46,09/08/2020 14:07
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,"187,9",340,3,None,19/12/2019 09:21,19/12/2019 10:51
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",3,"0,09",18/03/2019 15:40,23/03/2019 17:52

In [28]:
# importando um arquivo xml

df = pd.read_xml('/content/drive/MyDrive/!Data Python 2603/base_vendas.xml')
display(df)

,index,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,None,28/09/2020 16:19,05/10/2020 16:31
1,1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,None,07/03/2020 12:47,08/03/2020 12:47
2,2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,None,21/04/2019 10:48,23/04/2019 15:55
3,3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,None,07/05/2020 17:59,08/05/2020 14:31
4,4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,"88,9","189,9",3,None,04/11/2019 15:40,05/11/2019 10:40
2996,2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,"59,9","142,4",3,None,24/06/2019 09:04,24/06/2019 10:50
2997,2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,"49,9","95,9",3,None,08/08/2020 14:46,09/08/2020 14:07
2998,2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,"187,9",340,3,None,19/12/2019 09:21,19/12/2019 10:51
2999,2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",3,"0,09",18/03/2019 15:40,23/03/2019 17:52

In [29]:
# importando um arquivo excel
# por padrão ele lê a primeira pasta

df = pd.read_excel('/content/drive/MyDrive/!Data Python 2603/Vendas.xlsx')
display(df)

    matricula_funcionario  Nome Funcionario
0               123456111        José Maria
1               123456111        José Maria
2               123456222  Maria das Graças
3               123456333      Jorge Mateus
4               123456555        Marta Cury
5               123456444     Ricardo Lemos
6               123456666   Reginaldo Sodré
7               123456999    Felipe Marinho
8               123456777     Marcos Coelho
9               123456888      Rita Sampaio
10              123457112    Mário Henrique
11              123457111       Pamela Lima
12              123457113       Victor Hugo

In [30]:
# para ler outra pasta, usamos o parâmetro 'sheet_name=nome da pasta'

df = pd.read_excel('/content/drive/MyDrive/!Data Python 2603/Vendas.xlsx', sheet_name='base_vendas')
display(df)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,210.9,404.1,1,NaN,2020-09-28 16:19:00,2020-10-05 16:31:00
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,109.9,249.9,1,NaN,2020-03-07 12:47:00,2020-03-08 12:47:00
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,699.9,1346.9,1,NaN,2019-04-21 10:48:00,2019-04-23 15:55:00
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,899.9,1676.9,1,NaN,2020-05-07 17:59:00,2020-05-08 14:31:00
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,1,0.05,2019-08-14 16:56:00,2019-08-19 15:52:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,88.9,189.9,3,NaN,2019-11-04 15:40:00,2019-11-05 10:40:00
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,59.9,142.4,3,NaN,2019-06-24 09:04:00,2019-06-24 10:50:00
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,49.9,95.9,3,NaN,2020-08-08 14:46:00,2020-08-09 14:07:00
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,187.9,340.0,3,NaN,2019-12-19 09:21:00,2019-12-19 10:51:00
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,3,0.09,2019-03-18 15:40:00,2019-03-23 17:52:00

In [32]:
# verificando as pastas que o arquivo contém

planilhas = pd.read_excel('/content/drive/MyDrive/!Data Python 2603/Vendas.xlsx', sheet_name=None)
print(planilhas.keys())

dict_keys(['funcionarios', 'base_vendas'])