In [290]:
# manipulação de dados

import pandas as pd

In [291]:
df_vendas = pd.read_csv('/content/drive/MyDrive/!Data Python 2603/base_vendas.csv')
df_vendas.head(10)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
5,123456111,José Maria,Vendedor,CL001,Loja Matriz,10010,Fritadeira elétrica,Cozinha,"187,9",340,1,NaN,10/07/2019 15:11,11/07/2019 14:30
6,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,26/06/2019 11:03,28/06/2019 13:37
7,123456111,José Maria,Vendedor,CL001,Loja Matriz,10006,Aspirador de pó,Casa,"88,9","189,9",1,NaN,15/03/2020 13:00,16/03/2020 11:15
8,123456111,José Maria,Vendedor,CL001,Loja Matriz,10010,Fritadeira elétrica,Cozinha,"187,9",340,1,NaN,15/08/2020 11:36,15/08/2020 14:22
9,123456111,José Maria,Vendedor,CL001,Loja Matriz,10017,Cama Box,Casa,"1189,9","1899,5",1,NaN,06/03/2019 13:01,11/03/2019 12:01

In [292]:
# estrutura do arquivo

df_vendas.shape

(3000, 14)

In [293]:
#  mostrar as colunas e tipos de dados

df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   int64
 1   Nome Funcionario       3000 non-null   object
 2   Cargo                  3000 non-null   object
 3   codigo_loja            3000 non-null   object
 4   nome_loja              3000 non-null   object
 5   codigo_produto         3000 non-null   int64
 6   descricao_produto      3000 non-null   object
 7   Categoria              3000 non-null   object
 8   preco_custo            3000 non-null   object
 9   valor_unitario         3000 non-null   object
 10  quantidade             3000 non-null   int64
 11  comissao               159 non-null    object
 12  dt_venda               3000 non-null   object
 13  dt_entrega             3000 non-null   object
dtypes: int64(3), object(11)
memory usage: 328.3+ KB

In [294]:
# mostrar as colunas

df_vendas.columns

Index(['matricula_funcionario', 'Nome Funcionario', 'Cargo', 'codigo_loja',
       'nome_loja', 'codigo_produto', 'descricao_produto', 'Categoria',
       'preco_custo', 'valor_unitario', 'quantidade', 'comissao', 'dt_venda',
       'dt_entrega'],
      dtype='object')

In [295]:
# descrição do arquivo

df_vendas.describe().round(2)

       matricula_funcionario  codigo_produto  quantidade
count           3.000000e+03         3000.00     3000.00
mean            1.234567e+08        10010.47        2.45
std             3.490000e+02            5.77        1.11
min             1.234561e+08        10001.00        1.00
25%             1.234563e+08        10006.00        1.00
50%             1.234567e+08        10011.00        2.00
75%             1.234570e+08        10015.00        3.00
max             1.234571e+08        10020.00        4.00

In [296]:
# descriçao apenas dos campos 'object' (strings)

df_vendas.describe(include='object')

,Nome Funcionario,Cargo,codigo_loja,nome_loja,descricao_produto,Categoria,preco_custo,valor_unitario,comissao,dt_venda,dt_entrega
count,3000,3000,3000,3000,3000,3000,3000,3000,159,3000,3000
unique,12,1,4,4,20,4,20,19,4,2994,2989
top,José Maria,Vendedor,CL001,Loja Matriz,Aspirador de pó,Casa,"88,9","189,9","0,05",09/07/2019 16:05,09/12/2019 10:12
freq,280,3000,793,793,173,907,173,316,49,2,2

In [297]:
# descrição de todos os campos

df_vendas.describe(include='all').round(2)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
count,3.000000e+03,3000,3000,3000,3000,3000.00,3000,3000,3000,3000,3000.00,159,3000,3000
unique,NaN,12,1,4,4,NaN,20,4,20,19,NaN,4,2994,2989
top,NaN,José Maria,Vendedor,CL001,Loja Matriz,NaN,Aspirador de pó,Casa,"88,9","189,9",NaN,"0,05",09/07/2019 16:05,09/12/2019 10:12
freq,NaN,280,3000,793,793,NaN,173,907,173,316,NaN,49,2,2
mean,1.234567e+08,NaN,NaN,NaN,NaN,10010.47,NaN,NaN,NaN,NaN,2.45,NaN,NaN,NaN
std,3.490000e+02,NaN,NaN,NaN,NaN,5.77,NaN,NaN,NaN,NaN,1.11,NaN,NaN,NaN
min,1.234561e+08,NaN,NaN,NaN,NaN,10001.00,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN
25%,1.234563e+08,NaN,NaN,NaN,NaN,10006.00,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN
50%,1.234567e+08,NaN,NaN,NaN,NaN,10011.00,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN
75%,1.234570e+08,NaN,NaN,NaN,NaN,10015.00,NaN,NaN,NaN,NaN,3.00,NaN,NaN,NaN
max,1.234571e+08,NaN,NaN,NaN,NaN,10020.00,NaN,NaN,NaN,NaN,4.00,NaN,NaN,NaN

In [298]:
# alterando o tipo de dado de string (object) para datetime (ao trazer o arquivo)

df_vendas = pd.read_csv('/content/drive/MyDrive/!Data Python 2603/base_vendas.csv', parse_dates=['dt_venda'], dayfirst=True)

In [299]:
df_vendas['dt_venda'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 3000 entries, 0 to 2999
Series name: dt_venda
Non-Null Count  Dtype
--------------  -----
3000 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 23.6 KB

In [300]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   int64
 1   Nome Funcionario       3000 non-null   object
 2   Cargo                  3000 non-null   object
 3   codigo_loja            3000 non-null   object
 4   nome_loja              3000 non-null   object
 5   codigo_produto         3000 non-null   int64
 6   descricao_produto      3000 non-null   object
 7   Categoria              3000 non-null   object
 8   preco_custo            3000 non-null   object
 9   valor_unitario         3000 non-null   object
 10  quantidade             3000 non-null   int64
 11  comissao               159 non-null    object
 12  dt_venda               3000 non-null   datetime64[ns]
 13  dt_entrega             3000 non-null   object
dtypes: datetime64[ns](1), int64(3), object(10)
memory usage: 328.3+ KB

In [301]:
# alterando o tipo de dado de string (object) para datetime (maior controle)

df_vendas['dt_entrega'] = pd.to_datetime(df_vendas['dt_entrega'], format='%d/%m/%Y %H:%M')

In [302]:
df_vendas['dt_entrega'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 3000 entries, 0 to 2999
Series name: dt_entrega
Non-Null Count  Dtype
--------------  -----
3000 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 23.6 KB

In [303]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   int64
 1   Nome Funcionario       3000 non-null   object
 2   Cargo                  3000 non-null   object
 3   codigo_loja            3000 non-null   object
 4   nome_loja              3000 non-null   object
 5   codigo_produto         3000 non-null   int64
 6   descricao_produto      3000 non-null   object
 7   Categoria              3000 non-null   object
 8   preco_custo            3000 non-null   object
 9   valor_unitario         3000 non-null   object
 10  quantidade             3000 non-null   int64
 11  comissao               159 non-null    object
 12  dt_venda               3000 non-null   datetime64[ns]
 13  dt_entrega             3000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), int64(3), object(9)
memory usage: 328.3+ KB

In [304]:
df_vendas.head(10)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,2020-09-28 16:19:00,2020-10-05 16:31:00
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,2020-03-07 12:47:00,2020-03-08 12:47:00
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,2019-04-21 10:48:00,2019-04-23 15:55:00
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,2020-05-07 17:59:00,2020-05-08 14:31:00
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",2019-08-14 16:56:00,2019-08-19 15:52:00
5,123456111,José Maria,Vendedor,CL001,Loja Matriz,10010,Fritadeira elétrica,Cozinha,"187,9",340,1,NaN,2019-07-10 15:11:00,2019-07-11 14:30:00
6,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,2019-06-26 11:03:00,2019-06-28 13:37:00
7,123456111,José Maria,Vendedor,CL001,Loja Matriz,10006,Aspirador de pó,Casa,"88,9","189,9",1,NaN,2020-03-15 13:00:00,2020-03-16 11:15:00
8,123456111,José Maria,Vendedor,CL001,Loja Matriz,10010,Fritadeira elétrica,Cozinha,"187,9",340,1,NaN,2020-08-15 11:36:00,2020-08-15 14:22:00
9,123456111,José Maria,Vendedor,CL001,Loja Matriz,10017,Cama Box,Casa,"1189,9","1899,5",1,NaN,2019-03-06 13:01:00,2019-03-11 12:01:00

In [305]:
df_vendas.describe(include='all')

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
count,3.000000e+03,3000,3000,3000,3000,3000.000000,3000,3000,3000,3000,3000.000000,159,3000,3000
unique,NaN,12,1,4,4,NaN,20,4,20,19,NaN,4,NaN,NaN
top,NaN,José Maria,Vendedor,CL001,Loja Matriz,NaN,Aspirador de pó,Casa,"88,9","189,9",NaN,"0,05",NaN,NaN
freq,NaN,280,3000,793,793,NaN,173,907,173,316,NaN,49,NaN,NaN
mean,1.234567e+08,NaN,NaN,NaN,NaN,10010.468667,NaN,NaN,NaN,NaN,2.453333,NaN,2019-12-26 16:18:31.819999744,2019-12-28 13:30:03.600000
min,1.234561e+08,NaN,NaN,NaN,NaN,10001.000000,NaN,NaN,NaN,NaN,1.000000,NaN,2019-01-01 09:08:00,2019-01-01 14:07:00
25%,1.234563e+08,NaN,NaN,NaN,NaN,10006.000000,NaN,NaN,NaN,NaN,1.000000,NaN,2019-06-22 06:13:00,2019-06-25 05:15:15
50%,1.234567e+08,NaN,NaN,NaN,NaN,10011.000000,NaN,NaN,NaN,NaN,2.000000,NaN,2019-12-18 17:39:30,2019-12-21 10:46:00
75%,1.234570e+08,NaN,NaN,NaN,NaN,10015.000000,NaN,NaN,NaN,NaN,3.000000,NaN,2020-06-28 11:34:00,2020-06-30 15:31:45
max,1.234571e+08,NaN,NaN,NaN,NaN,10020.000000,NaN,NaN,NaN,NaN,4.000000,NaN,2020-12-31 15:07:00,2020-12-31 17:37:00
std,3.489977e+02,NaN,NaN,NaN,NaN,5.772590,NaN,NaN,NaN,NaN,1.107955,NaN,NaN,NaN

In [306]:
# trocando a vírgula por ponto dentro da string (object)

df_vendas['preco_custo'] = df_vendas['preco_custo'].str.replace(',', '.')
df_vendas['preco_custo'].head(8)

0    210.9
1    109.9
2    699.9
3    899.9
4     1099
5    187.9
6    699.9
7     88.9
Name: preco_custo, dtype: object

In [307]:
# alterando o tipo de dado de string (object) para decimal (float)

df_vendas['preco_custo'] = df_vendas['preco_custo'].astype(float)
df_vendas['preco_custo'].head(8)

0     210.9
1     109.9
2     699.9
3     899.9
4    1099.0
5     187.9
6     699.9
7      88.9
Name: preco_custo, dtype: float64

In [308]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   int64
 1   Nome Funcionario       3000 non-null   object
 2   Cargo                  3000 non-null   object
 3   codigo_loja            3000 non-null   object
 4   nome_loja              3000 non-null   object
 5   codigo_produto         3000 non-null   int64
 6   descricao_produto      3000 non-null   object
 7   Categoria              3000 non-null   object
 8   preco_custo            3000 non-null   float64
 9   valor_unitario         3000 non-null   object
 10  quantidade             3000 non-null   int64
 11  comissao               159 non-null    object
 12  dt_venda               3000 non-null   datetime64[ns]
 13  dt_entrega             3000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(3), object(8)
memory usage: 328.3+ KB

In [309]:
#  trocando a vírgula por ponto dentro da string (object) e
# alterando o tipo de dado para decimal (float) ao mesmo tempo

df_vendas['valor_unitario'] = df_vendas['valor_unitario'].str.replace(',', '.').astype(float)
df_vendas['valor_unitario'].head(8)

0     404.1
1     249.9
2    1346.9
3    1676.9
4    1709.1
5     340.0
6    1346.9
7     189.9
Name: valor_unitario, dtype: float64

In [310]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   int64
 1   Nome Funcionario       3000 non-null   object
 2   Cargo                  3000 non-null   object
 3   codigo_loja            3000 non-null   object
 4   nome_loja              3000 non-null   object
 5   codigo_produto         3000 non-null   int64
 6   descricao_produto      3000 non-null   object
 7   Categoria              3000 non-null   object
 8   preco_custo            3000 non-null   float64
 9   valor_unitario         3000 non-null   float64
 10  quantidade             3000 non-null   int64
 11  comissao               159 non-null    object
 12  dt_venda               3000 non-null   datetime64[ns]
 13  dt_entrega             3000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(2), int64(3), object(7)
memory usage: 328.3+ KB

In [311]:
df_vendas.describe(include='all').round(2)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
count,3.000000e+03,3000,3000,3000,3000,3000.00,3000,3000,3000.00,3000.00,3000.00,159,3000,3000
unique,NaN,12,1,4,4,NaN,20,4,NaN,NaN,NaN,4,NaN,NaN
top,NaN,José Maria,Vendedor,CL001,Loja Matriz,NaN,Aspirador de pó,Casa,NaN,NaN,NaN,"0,05",NaN,NaN
freq,NaN,280,3000,793,793,NaN,173,907,NaN,NaN,NaN,49,NaN,NaN
mean,1.234567e+08,NaN,NaN,NaN,NaN,10010.47,NaN,NaN,545.51,926.94,2.45,NaN,2019-12-26 16:18:31.819999744,2019-12-28 13:30:03.600000
min,1.234561e+08,NaN,NaN,NaN,NaN,10001.00,NaN,NaN,27.90,55.90,1.00,NaN,2019-01-01 09:08:00,2019-01-01 14:07:00
25%,1.234563e+08,NaN,NaN,NaN,NaN,10006.00,NaN,NaN,109.90,189.90,1.00,NaN,2019-06-22 06:13:00,2019-06-25 05:15:15
50%,1.234567e+08,NaN,NaN,NaN,NaN,10011.00,NaN,NaN,210.90,404.10,2.00,NaN,2019-12-18 17:39:30,2019-12-21 10:46:00
75%,1.234570e+08,NaN,NaN,NaN,NaN,10015.00,NaN,NaN,799.00,1424.91,3.00,NaN,2020-06-28 11:34:00,2020-06-30 15:31:45
max,1.234571e+08,NaN,NaN,NaN,NaN,10020.00,NaN,NaN,2299.90,3199.00,4.00,NaN,2020-12-31 15:07:00,2020-12-31 17:37:00
std,3.490000e+02,NaN,NaN,NaN,NaN,5.77,NaN,NaN,563.13,841.84,1.11,NaN,NaN,NaN

In [312]:
# alterando o tipo de dado numérico (int) para string (object)
# posso fazer isso em mais de uma coluna ao mesmo tempo

df_vendas = df_vendas.astype({
                        'matricula_funcionario':str,
                        'codigo_produto':str
                        })
df_vendas[['matricula_funcionario','codigo_produto']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   object
 1   codigo_produto         3000 non-null   object
dtypes: object(2)
memory usage: 47.0+ KB

In [313]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   object
 1   Nome Funcionario       3000 non-null   object
 2   Cargo                  3000 non-null   object
 3   codigo_loja            3000 non-null   object
 4   nome_loja              3000 non-null   object
 5   codigo_produto         3000 non-null   object
 6   descricao_produto      3000 non-null   object
 7   Categoria              3000 non-null   object
 8   preco_custo            3000 non-null   float64
 9   valor_unitario         3000 non-null   float64
 10  quantidade             3000 non-null   int64
 11  comissao               159 non-null    object
 12  dt_venda               3000 non-null   datetime64[ns]
 13  dt_entrega             3000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(2), int64(1), object(9)
memory usage: 328.3+ KB

In [314]:
df_vendas['comissao'] = df_vendas['comissao'].str.replace(',', '.').astype(float)
df_vendas['comissao'].head(8)

0     NaN
1     NaN
2     NaN
3     NaN
4    0.05
5     NaN
6     NaN
7     NaN
Name: comissao, dtype: float64

In [315]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   object
 1   Nome Funcionario       3000 non-null   object
 2   Cargo                  3000 non-null   object
 3   codigo_loja            3000 non-null   object
 4   nome_loja              3000 non-null   object
 5   codigo_produto         3000 non-null   object
 6   descricao_produto      3000 non-null   object
 7   Categoria              3000 non-null   object
 8   preco_custo            3000 non-null   float64
 9   valor_unitario         3000 non-null   float64
 10  quantidade             3000 non-null   int64
 11  comissao               159 non-null    float64
 12  dt_venda               3000 non-null   datetime64[ns]
 13  dt_entrega             3000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(3), int64(1), object(8)
memory usage: 328.3+ KB

In [316]:
display(df_vendas)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,210.9,404.1,1,NaN,2020-09-28 16:19:00,2020-10-05 16:31:00
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,109.9,249.9,1,NaN,2020-03-07 12:47:00,2020-03-08 12:47:00
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,699.9,1346.9,1,NaN,2019-04-21 10:48:00,2019-04-23 15:55:00
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,899.9,1676.9,1,NaN,2020-05-07 17:59:00,2020-05-08 14:31:00
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,1,0.05,2019-08-14 16:56:00,2019-08-19 15:52:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,88.9,189.9,3,NaN,2019-11-04 15:40:00,2019-11-05 10:40:00
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,59.9,142.4,3,NaN,2019-06-24 09:04:00,2019-06-24 10:50:00
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,49.9,95.9,3,NaN,2020-08-08 14:46:00,2020-08-09 14:07:00
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,187.9,340.0,3,NaN,2019-12-19 09:21:00,2019-12-19 10:51:00
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,3,0.09,2019-03-18 15:40:00,2019-03-23 17:52:00

In [317]:
# Padronizar o nome das colunas (parte 1)

nome_colunas = df_vendas.columns
print(type(nome_colunas))
print(nome_colunas)

<class 'pandas.core.indexes.base.Index'>
Index(['matricula_funcionario', 'Nome Funcionario', 'Cargo', 'codigo_loja',
       'nome_loja', 'codigo_produto', 'descricao_produto', 'Categoria',
       'preco_custo', 'valor_unitario', 'quantidade', 'comissao', 'dt_venda',
       'dt_entrega'],
      dtype='object')

In [318]:
# Padronizar o nome das colunas (parte 2)

df_vendas.columns = list(i.strip().lower().replace(' ','_') for i in nome_colunas)
print(df_vendas.columns)

Index(['matricula_funcionario', 'nome_funcionario', 'cargo', 'codigo_loja',
       'nome_loja', 'codigo_produto', 'descricao_produto', 'categoria',
       'preco_custo', 'valor_unitario', 'quantidade', 'comissao', 'dt_venda',
       'dt_entrega'],
      dtype='object')

In [319]:
print(
    'Máximo: ', df_vendas['comissao'].max(),
    '\nMínimo: ', df_vendas['comissao'].min(),
    '\nMediana: ', df_vendas['comissao'].median(),
    '\nMédia: ', df_vendas['comissao'].mean(),
    '\nModa: ',df_vendas['comissao'].mode()
)

Máximo:  0.1
Mínimo:  0.05
Mediana:  0.07
Média:  0.07446540880503144
Moda:  0    0.05
Name: comissao, dtype: float64

In [320]:
# tratamento do campo 'comissao'

df_vendas['comissao']

0        NaN
1        NaN
2        NaN
3        NaN
4       0.05
        ...
2995     NaN
2996     NaN
2997     NaN
2998     NaN
2999    0.09
Name: comissao, Length: 3000, dtype: float64

In [321]:
# preenchimento dos valores nulos do campo 'comissao' de forma manual

df_vendas['comissao'].fillna(0, inplace=True)
# df_vendas['comissao']

In [322]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   object
 1   nome_funcionario       3000 non-null   object
 2   cargo                  3000 non-null   object
 3   codigo_loja            3000 non-null   object
 4   nome_loja              3000 non-null   object
 5   codigo_produto         3000 non-null   object
 6   descricao_produto      3000 non-null   object
 7   categoria              3000 non-null   object
 8   preco_custo            3000 non-null   float64
 9   valor_unitario         3000 non-null   float64
 10  quantidade             3000 non-null   int64
 11  comissao               3000 non-null   float64
 12  dt_venda               3000 non-null   datetime64[ns]
 13  dt_entrega             3000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(3), int64(1), object(8)
memory usage: 328.3+ KB

In [323]:
# preenchimento dos valores nulos do campo 'comissao' com o último valor de cima para baixo
# ffill() #forward

# df_vendas['comissao'].ffill(inplace=True)
# df_vendas

In [324]:
# preenchimento dos valores nulos do campo 'comissao' com o último valor de baixo para cima
# bfill() #backward

# df_vendas['comissao'].bfill(inplace=True)
df_vendas

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,210.9,404.1,1,0.00,2020-09-28 16:19:00,2020-10-05 16:31:00
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,109.9,249.9,1,0.00,2020-03-07 12:47:00,2020-03-08 12:47:00
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,699.9,1346.9,1,0.00,2019-04-21 10:48:00,2019-04-23 15:55:00
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,899.9,1676.9,1,0.00,2020-05-07 17:59:00,2020-05-08 14:31:00
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,1,0.05,2019-08-14 16:56:00,2019-08-19 15:52:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,88.9,189.9,3,0.00,2019-11-04 15:40:00,2019-11-05 10:40:00
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,59.9,142.4,3,0.00,2019-06-24 09:04:00,2019-06-24 10:50:00
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,49.9,95.9,3,0.00,2020-08-08 14:46:00,2020-08-09 14:07:00
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,187.9,340.0,3,0.00,2019-12-19 09:21:00,2019-12-19 10:51:00
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,3,0.09,2019-03-18 15:40:00,2019-03-23 17:52:00

In [325]:
# remover as linhas que possuem valores NaN (Not a number / nulos)

# df_vendas.dropna(inplace=True)

In [326]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   object
 1   nome_funcionario       3000 non-null   object
 2   cargo                  3000 non-null   object
 3   codigo_loja            3000 non-null   object
 4   nome_loja              3000 non-null   object
 5   codigo_produto         3000 non-null   object
 6   descricao_produto      3000 non-null   object
 7   categoria              3000 non-null   object
 8   preco_custo            3000 non-null   float64
 9   valor_unitario         3000 non-null   float64
 10  quantidade             3000 non-null   int64
 11  comissao               3000 non-null   float64
 12  dt_venda               3000 non-null   datetime64[ns]
 13  dt_entrega             3000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(3), int64(1), object(8)
memory usage: 328.3+ KB

In [327]:
# removendo linhas duplicadas

data = {
    'coluna1':[1,2,2,3,4,4,5],
    'coluna2':['A','B','B','C','D','D','J'],
    'coluna3':['1','2','2','3','4','4','5']
}
# print(type(data))

df_duplicados = pd.DataFrame(data)
display(df_duplicados)

df_duplicados.drop_duplicates(inplace=True)
display(df_duplicados)

   coluna1 coluna2 coluna3
0        1       A       1
1        2       B       2
2        2       B       2
3        3       C       3
4        4       D       4
5        4       D       4
6        5       J       5

   coluna1 coluna2 coluna3
0        1       A       1
1        2       B       2
3        3       C       3
4        4       D       4
6        5       J       5

In [328]:
df_vendas.head(20)

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,210.9,404.10,1,0.00,2020-09-28 16:19:00,2020-10-05 16:31:00
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,109.9,249.90,1,0.00,2020-03-07 12:47:00,2020-03-08 12:47:00
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,699.9,1346.90,1,0.00,2019-04-21 10:48:00,2019-04-23 15:55:00
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,899.9,1676.90,1,0.00,2020-05-07 17:59:00,2020-05-08 14:31:00
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.10,1,0.05,2019-08-14 16:56:00,2019-08-19 15:52:00
5,123456111,José Maria,Vendedor,CL001,Loja Matriz,10010,Fritadeira elétrica,Cozinha,187.9,340.00,1,0.00,2019-07-10 15:11:00,2019-07-11 14:30:00
6,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,699.9,1346.90,1,0.00,2019-06-26 11:03:00,2019-06-28 13:37:00
7,123456111,José Maria,Vendedor,CL001,Loja Matriz,10006,Aspirador de pó,Casa,88.9,189.90,1,0.00,2020-03-15 13:00:00,2020-03-16 11:15:00
8,123456111,José Maria,Vendedor,CL001,Loja Matriz,10010,Fritadeira elétrica,Cozinha,187.9,340.00,1,0.00,2020-08-15 11:36:00,2020-08-15 14:22:00
9,123456111,José Maria,Vendedor,CL001,Loja Matriz,10017,Cama Box,Casa,1189.9,1899.50,1,0.00,2019-03-06 13:01:00,2019-03-11 12:01:00
10,123456111,José Maria,Vendedor,CL001,Loja Matriz,10003,Televisão,Eletrodomésticos,1400.9,2279.99,1,0.00,2019-10-11 12:44:00,2019-10-17 14:58:00
11,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.10,1,0.05,2019-10-30 17:22:00,2019-11-03 10:21:00
12,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,109.9,249.90,1,0.00,2020-05-28 16:00:00,2020-05-29 14:16:00
13,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,210.9,404.10,1,0.00,2019-12-30 15:07:00,2020-01-04 16:48:00
14,123456111,José Maria,Vendedor,CL001,Loja Matriz,10016,Guarda Roupa,Casa,489.9,999.00,1,0.00,2019-04-16 09:22:00,2019-04-23 10:49:00
15,123456111,José Maria,Vendedor,CL001,Loja Matriz,10020,Impressora,Eletrônicos,329.9,674.10,1,0.00,2019-09-07 15:29:00,2019-09-08 13:00:00
16,123456111,José Maria,Vendedor,CL001,Loja Matriz,10017,Cama Box,Casa,1189.9,1899.50,1,0.00,2019-03-18 09:08:00,2019-03-25 15:58:00
17,123456111,José Maria,Vendedor,CL001,Loja Matriz,10008,Cafeteira,Cozinha,159.9,284.90,1,0.00,2020-01-28 16:40:00,2020-01-29 11:59:00
18,123456111,José Maria,Vendedor,CL001,Loja Matriz,10015,Microondas,Eletrodomésticos,189.0,364.50,1,0.00,2020-10-30 17:27:00,2020-10-31 14:16:00
19,123456111,José Maria,Vendedor,CL001,Loja Matriz,10016,Guarda Roupa,Casa,489.9,999.00,1,0.00,2020-10-23 17:41:00,2020-10-30 09:27:00

In [329]:
# eliminando colunas do DataFrame

df_vendas.drop(columns=['matricula_funcionario','codigo_produto'], inplace=True)

In [330]:
df_vendas

,nome_funcionario,cargo,codigo_loja,nome_loja,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,José Maria,Vendedor,CL001,Loja Matriz,Fogão,Eletrodomésticos,210.9,404.1,1,0.00,2020-09-28 16:19:00,2020-10-05 16:31:00
1,José Maria,Vendedor,CL001,Loja Matriz,Colchão,Casa,109.9,249.9,1,0.00,2020-03-07 12:47:00,2020-03-08 12:47:00
2,José Maria,Vendedor,CL001,Loja Matriz,Geladeira,Eletrodomésticos,699.9,1346.9,1,0.00,2019-04-21 10:48:00,2019-04-23 15:55:00
3,José Maria,Vendedor,CL001,Loja Matriz,Smartphone,Eletrônicos,899.9,1676.9,1,0.00,2020-05-07 17:59:00,2020-05-08 14:31:00
4,José Maria,Vendedor,CL001,Loja Matriz,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,1,0.05,2019-08-14 16:56:00,2019-08-19 15:52:00
...,...,...,...,...,...,...,...,...,...,...,...,...
2995,Victor Hugo,Vendedor,CL004,Filial ES,Aspirador de pó,Casa,88.9,189.9,3,0.00,2019-11-04 15:40:00,2019-11-05 10:40:00
2996,Victor Hugo,Vendedor,CL004,Filial ES,Liquidificador,Cozinha,59.9,142.4,3,0.00,2019-06-24 09:04:00,2019-06-24 10:50:00
2997,Victor Hugo,Vendedor,CL004,Filial ES,Batedeira,Cozinha,49.9,95.9,3,0.00,2020-08-08 14:46:00,2020-08-09 14:07:00
2998,Victor Hugo,Vendedor,CL004,Filial ES,Fritadeira elétrica,Cozinha,187.9,340.0,3,0.00,2019-12-19 09:21:00,2019-12-19 10:51:00
2999,Victor Hugo,Vendedor,CL004,Filial ES,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,3,0.09,2019-03-18 15:40:00,2019-03-23 17:52:00

In [331]:
# ENGENHARIA DE DADOS / DATA ENGINEER
# Criando novas colunas no DataFrame
# 1 ) coluna --> valor_final

df_vendas['valor_final'] = df_vendas['quantidade'] * df_vendas['valor_unitario']
df_vendas

,nome_funcionario,cargo,codigo_loja,nome_loja,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega,valor_final
0,José Maria,Vendedor,CL001,Loja Matriz,Fogão,Eletrodomésticos,210.9,404.1,1,0.00,2020-09-28 16:19:00,2020-10-05 16:31:00,404.1
1,José Maria,Vendedor,CL001,Loja Matriz,Colchão,Casa,109.9,249.9,1,0.00,2020-03-07 12:47:00,2020-03-08 12:47:00,249.9
2,José Maria,Vendedor,CL001,Loja Matriz,Geladeira,Eletrodomésticos,699.9,1346.9,1,0.00,2019-04-21 10:48:00,2019-04-23 15:55:00,1346.9
3,José Maria,Vendedor,CL001,Loja Matriz,Smartphone,Eletrônicos,899.9,1676.9,1,0.00,2020-05-07 17:59:00,2020-05-08 14:31:00,1676.9
4,José Maria,Vendedor,CL001,Loja Matriz,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,1,0.05,2019-08-14 16:56:00,2019-08-19 15:52:00,1709.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,Victor Hugo,Vendedor,CL004,Filial ES,Aspirador de pó,Casa,88.9,189.9,3,0.00,2019-11-04 15:40:00,2019-11-05 10:40:00,569.7
2996,Victor Hugo,Vendedor,CL004,Filial ES,Liquidificador,Cozinha,59.9,142.4,3,0.00,2019-06-24 09:04:00,2019-06-24 10:50:00,427.2
2997,Victor Hugo,Vendedor,CL004,Filial ES,Batedeira,Cozinha,49.9,95.9,3,0.00,2020-08-08 14:46:00,2020-08-09 14:07:00,287.7
2998,Victor Hugo,Vendedor,CL004,Filial ES,Fritadeira elétrica,Cozinha,187.9,340.0,3,0.00,2019-12-19 09:21:00,2019-12-19 10:51:00,1020.0
2999,Victor Hugo,Vendedor,CL004,Filial ES,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,3,0.09,2019-03-18 15:40:00,2019-03-23 17:52:00,5127.3

In [332]:
# 2 ) coluna --> lucro_sem_comissao (lucro sem deduzir a comissão do vendedor)

# df_vendas.insert(9, 'lucro_sem_comissao', (df_vendas['valor_unitario'] - df_vendas['preco_custo']) * df_vendas['quantidade'])

df_vendas['lucro_sem_comissao'] = (df_vendas['valor_unitario'] - df_vendas['preco_custo']) * df_vendas['quantidade']
df_vendas

,nome_funcionario,cargo,codigo_loja,nome_loja,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega,valor_final,lucro_sem_comissao
0,José Maria,Vendedor,CL001,Loja Matriz,Fogão,Eletrodomésticos,210.9,404.1,1,0.00,2020-09-28 16:19:00,2020-10-05 16:31:00,404.1,193.2
1,José Maria,Vendedor,CL001,Loja Matriz,Colchão,Casa,109.9,249.9,1,0.00,2020-03-07 12:47:00,2020-03-08 12:47:00,249.9,140.0
2,José Maria,Vendedor,CL001,Loja Matriz,Geladeira,Eletrodomésticos,699.9,1346.9,1,0.00,2019-04-21 10:48:00,2019-04-23 15:55:00,1346.9,647.0
3,José Maria,Vendedor,CL001,Loja Matriz,Smartphone,Eletrônicos,899.9,1676.9,1,0.00,2020-05-07 17:59:00,2020-05-08 14:31:00,1676.9,777.0
4,José Maria,Vendedor,CL001,Loja Matriz,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,1,0.05,2019-08-14 16:56:00,2019-08-19 15:52:00,1709.1,610.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,Victor Hugo,Vendedor,CL004,Filial ES,Aspirador de pó,Casa,88.9,189.9,3,0.00,2019-11-04 15:40:00,2019-11-05 10:40:00,569.7,303.0
2996,Victor Hugo,Vendedor,CL004,Filial ES,Liquidificador,Cozinha,59.9,142.4,3,0.00,2019-06-24 09:04:00,2019-06-24 10:50:00,427.2,247.5
2997,Victor Hugo,Vendedor,CL004,Filial ES,Batedeira,Cozinha,49.9,95.9,3,0.00,2020-08-08 14:46:00,2020-08-09 14:07:00,287.7,138.0
2998,Victor Hugo,Vendedor,CL004,Filial ES,Fritadeira elétrica,Cozinha,187.9,340.0,3,0.00,2019-12-19 09:21:00,2019-12-19 10:51:00,1020.0,456.3
2999,Victor Hugo,Vendedor,CL004,Filial ES,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,3,0.09,2019-03-18 15:40:00,2019-03-23 17:52:00,5127.3,1830.3

In [333]:
# 3 ) coluna --> valor_comissao

df_vendas['valor_comissao'] = (df_vendas['valor_final'] * df_vendas['comissao']).round(2)
df_vendas

,nome_funcionario,cargo,codigo_loja,nome_loja,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega,valor_final,lucro_sem_comissao,valor_comissao
0,José Maria,Vendedor,CL001,Loja Matriz,Fogão,Eletrodomésticos,210.9,404.1,1,0.00,2020-09-28 16:19:00,2020-10-05 16:31:00,404.1,193.2,0.00
1,José Maria,Vendedor,CL001,Loja Matriz,Colchão,Casa,109.9,249.9,1,0.00,2020-03-07 12:47:00,2020-03-08 12:47:00,249.9,140.0,0.00
2,José Maria,Vendedor,CL001,Loja Matriz,Geladeira,Eletrodomésticos,699.9,1346.9,1,0.00,2019-04-21 10:48:00,2019-04-23 15:55:00,1346.9,647.0,0.00
3,José Maria,Vendedor,CL001,Loja Matriz,Smartphone,Eletrônicos,899.9,1676.9,1,0.00,2020-05-07 17:59:00,2020-05-08 14:31:00,1676.9,777.0,0.00
4,José Maria,Vendedor,CL001,Loja Matriz,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,1,0.05,2019-08-14 16:56:00,2019-08-19 15:52:00,1709.1,610.1,85.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,Victor Hugo,Vendedor,CL004,Filial ES,Aspirador de pó,Casa,88.9,189.9,3,0.00,2019-11-04 15:40:00,2019-11-05 10:40:00,569.7,303.0,0.00
2996,Victor Hugo,Vendedor,CL004,Filial ES,Liquidificador,Cozinha,59.9,142.4,3,0.00,2019-06-24 09:04:00,2019-06-24 10:50:00,427.2,247.5,0.00
2997,Victor Hugo,Vendedor,CL004,Filial ES,Batedeira,Cozinha,49.9,95.9,3,0.00,2020-08-08 14:46:00,2020-08-09 14:07:00,287.7,138.0,0.00
2998,Victor Hugo,Vendedor,CL004,Filial ES,Fritadeira elétrica,Cozinha,187.9,340.0,3,0.00,2019-12-19 09:21:00,2019-12-19 10:51:00,1020.0,456.3,0.00
2999,Victor Hugo,Vendedor,CL004,Filial ES,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,3,0.09,2019-03-18 15:40:00,2019-03-23 17:52:00,5127.3,1830.3,461.46

In [334]:
# 4 ) coluna --> lucro_real

df_vendas['lucro_real'] = df_vendas['lucro_sem_comissao'] - df_vendas['valor_comissao']
df_vendas

,nome_funcionario,cargo,codigo_loja,nome_loja,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega,valor_final,lucro_sem_comissao,valor_comissao,lucro_real
0,José Maria,Vendedor,CL001,Loja Matriz,Fogão,Eletrodomésticos,210.9,404.1,1,0.00,2020-09-28 16:19:00,2020-10-05 16:31:00,404.1,193.2,0.00,193.20
1,José Maria,Vendedor,CL001,Loja Matriz,Colchão,Casa,109.9,249.9,1,0.00,2020-03-07 12:47:00,2020-03-08 12:47:00,249.9,140.0,0.00,140.00
2,José Maria,Vendedor,CL001,Loja Matriz,Geladeira,Eletrodomésticos,699.9,1346.9,1,0.00,2019-04-21 10:48:00,2019-04-23 15:55:00,1346.9,647.0,0.00,647.00
3,José Maria,Vendedor,CL001,Loja Matriz,Smartphone,Eletrônicos,899.9,1676.9,1,0.00,2020-05-07 17:59:00,2020-05-08 14:31:00,1676.9,777.0,0.00,777.00
4,José Maria,Vendedor,CL001,Loja Matriz,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,1,0.05,2019-08-14 16:56:00,2019-08-19 15:52:00,1709.1,610.1,85.46,524.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,Victor Hugo,Vendedor,CL004,Filial ES,Aspirador de pó,Casa,88.9,189.9,3,0.00,2019-11-04 15:40:00,2019-11-05 10:40:00,569.7,303.0,0.00,303.00
2996,Victor Hugo,Vendedor,CL004,Filial ES,Liquidificador,Cozinha,59.9,142.4,3,0.00,2019-06-24 09:04:00,2019-06-24 10:50:00,427.2,247.5,0.00,247.50
2997,Victor Hugo,Vendedor,CL004,Filial ES,Batedeira,Cozinha,49.9,95.9,3,0.00,2020-08-08 14:46:00,2020-08-09 14:07:00,287.7,138.0,0.00,138.00
2998,Victor Hugo,Vendedor,CL004,Filial ES,Fritadeira elétrica,Cozinha,187.9,340.0,3,0.00,2019-12-19 09:21:00,2019-12-19 10:51:00,1020.0,456.3,0.00,456.30
2999,Victor Hugo,Vendedor,CL004,Filial ES,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,3,0.09,2019-03-18 15:40:00,2019-03-23 17:52:00,5127.3,1830.3,461.46,1368.84

In [335]:
df_vendas

,nome_funcionario,cargo,codigo_loja,nome_loja,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega,valor_final,lucro_sem_comissao,valor_comissao,lucro_real
0,José Maria,Vendedor,CL001,Loja Matriz,Fogão,Eletrodomésticos,210.9,404.1,1,0.00,2020-09-28 16:19:00,2020-10-05 16:31:00,404.1,193.2,0.00,193.20
1,José Maria,Vendedor,CL001,Loja Matriz,Colchão,Casa,109.9,249.9,1,0.00,2020-03-07 12:47:00,2020-03-08 12:47:00,249.9,140.0,0.00,140.00
2,José Maria,Vendedor,CL001,Loja Matriz,Geladeira,Eletrodomésticos,699.9,1346.9,1,0.00,2019-04-21 10:48:00,2019-04-23 15:55:00,1346.9,647.0,0.00,647.00
3,José Maria,Vendedor,CL001,Loja Matriz,Smartphone,Eletrônicos,899.9,1676.9,1,0.00,2020-05-07 17:59:00,2020-05-08 14:31:00,1676.9,777.0,0.00,777.00
4,José Maria,Vendedor,CL001,Loja Matriz,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,1,0.05,2019-08-14 16:56:00,2019-08-19 15:52:00,1709.1,610.1,85.46,524.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,Victor Hugo,Vendedor,CL004,Filial ES,Aspirador de pó,Casa,88.9,189.9,3,0.00,2019-11-04 15:40:00,2019-11-05 10:40:00,569.7,303.0,0.00,303.00
2996,Victor Hugo,Vendedor,CL004,Filial ES,Liquidificador,Cozinha,59.9,142.4,3,0.00,2019-06-24 09:04:00,2019-06-24 10:50:00,427.2,247.5,0.00,247.50
2997,Victor Hugo,Vendedor,CL004,Filial ES,Batedeira,Cozinha,49.9,95.9,3,0.00,2020-08-08 14:46:00,2020-08-09 14:07:00,287.7,138.0,0.00,138.00
2998,Victor Hugo,Vendedor,CL004,Filial ES,Fritadeira elétrica,Cozinha,187.9,340.0,3,0.00,2019-12-19 09:21:00,2019-12-19 10:51:00,1020.0,456.3,0.00,456.30
2999,Victor Hugo,Vendedor,CL004,Filial ES,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,3,0.09,2019-03-18 15:40:00,2019-03-23 17:52:00,5127.3,1830.3,461.46,1368.84

In [336]:
# 5 ) colunas --> margem_lucro

df_vendas['margem_lucro'] = ((df_vendas['valor_unitario'] - df_vendas['preco_custo'])/ df_vendas['valor_unitario']).round(2)
df_vendas

,nome_funcionario,cargo,codigo_loja,nome_loja,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega,valor_final,lucro_sem_comissao,valor_comissao,lucro_real,margem_lucro
0,José Maria,Vendedor,CL001,Loja Matriz,Fogão,Eletrodomésticos,210.9,404.1,1,0.00,2020-09-28 16:19:00,2020-10-05 16:31:00,404.1,193.2,0.00,193.20,0.48
1,José Maria,Vendedor,CL001,Loja Matriz,Colchão,Casa,109.9,249.9,1,0.00,2020-03-07 12:47:00,2020-03-08 12:47:00,249.9,140.0,0.00,140.00,0.56
2,José Maria,Vendedor,CL001,Loja Matriz,Geladeira,Eletrodomésticos,699.9,1346.9,1,0.00,2019-04-21 10:48:00,2019-04-23 15:55:00,1346.9,647.0,0.00,647.00,0.48
3,José Maria,Vendedor,CL001,Loja Matriz,Smartphone,Eletrônicos,899.9,1676.9,1,0.00,2020-05-07 17:59:00,2020-05-08 14:31:00,1676.9,777.0,0.00,777.00,0.46
4,José Maria,Vendedor,CL001,Loja Matriz,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,1,0.05,2019-08-14 16:56:00,2019-08-19 15:52:00,1709.1,610.1,85.46,524.64,0.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,Victor Hugo,Vendedor,CL004,Filial ES,Aspirador de pó,Casa,88.9,189.9,3,0.00,2019-11-04 15:40:00,2019-11-05 10:40:00,569.7,303.0,0.00,303.00,0.53
2996,Victor Hugo,Vendedor,CL004,Filial ES,Liquidificador,Cozinha,59.9,142.4,3,0.00,2019-06-24 09:04:00,2019-06-24 10:50:00,427.2,247.5,0.00,247.50,0.58
2997,Victor Hugo,Vendedor,CL004,Filial ES,Batedeira,Cozinha,49.9,95.9,3,0.00,2020-08-08 14:46:00,2020-08-09 14:07:00,287.7,138.0,0.00,138.00,0.48
2998,Victor Hugo,Vendedor,CL004,Filial ES,Fritadeira elétrica,Cozinha,187.9,340.0,3,0.00,2019-12-19 09:21:00,2019-12-19 10:51:00,1020.0,456.3,0.00,456.30,0.45
2999,Victor Hugo,Vendedor,CL004,Filial ES,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,3,0.09,2019-03-18 15:40:00,2019-03-23 17:52:00,5127.3,1830.3,461.46,1368.84,0.36

In [337]:
df_vendas['margem_lucro2'] = df_vendas['margem_lucro'] * 100

In [338]:
df_vendas

,nome_funcionario,cargo,codigo_loja,nome_loja,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega,valor_final,lucro_sem_comissao,valor_comissao,lucro_real,margem_lucro,margem_lucro2
0,José Maria,Vendedor,CL001,Loja Matriz,Fogão,Eletrodomésticos,210.9,404.1,1,0.00,2020-09-28 16:19:00,2020-10-05 16:31:00,404.1,193.2,0.00,193.20,0.48,48.0
1,José Maria,Vendedor,CL001,Loja Matriz,Colchão,Casa,109.9,249.9,1,0.00,2020-03-07 12:47:00,2020-03-08 12:47:00,249.9,140.0,0.00,140.00,0.56,56.0
2,José Maria,Vendedor,CL001,Loja Matriz,Geladeira,Eletrodomésticos,699.9,1346.9,1,0.00,2019-04-21 10:48:00,2019-04-23 15:55:00,1346.9,647.0,0.00,647.00,0.48,48.0
3,José Maria,Vendedor,CL001,Loja Matriz,Smartphone,Eletrônicos,899.9,1676.9,1,0.00,2020-05-07 17:59:00,2020-05-08 14:31:00,1676.9,777.0,0.00,777.00,0.46,46.0
4,José Maria,Vendedor,CL001,Loja Matriz,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,1,0.05,2019-08-14 16:56:00,2019-08-19 15:52:00,1709.1,610.1,85.46,524.64,0.36,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,Victor Hugo,Vendedor,CL004,Filial ES,Aspirador de pó,Casa,88.9,189.9,3,0.00,2019-11-04 15:40:00,2019-11-05 10:40:00,569.7,303.0,0.00,303.00,0.53,53.0
2996,Victor Hugo,Vendedor,CL004,Filial ES,Liquidificador,Cozinha,59.9,142.4,3,0.00,2019-06-24 09:04:00,2019-06-24 10:50:00,427.2,247.5,0.00,247.50,0.58,58.0
2997,Victor Hugo,Vendedor,CL004,Filial ES,Batedeira,Cozinha,49.9,95.9,3,0.00,2020-08-08 14:46:00,2020-08-09 14:07:00,287.7,138.0,0.00,138.00,0.48,48.0
2998,Victor Hugo,Vendedor,CL004,Filial ES,Fritadeira elétrica,Cozinha,187.9,340.0,3,0.00,2019-12-19 09:21:00,2019-12-19 10:51:00,1020.0,456.3,0.00,456.30,0.45,45.0
2999,Victor Hugo,Vendedor,CL004,Filial ES,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,3,0.09,2019-03-18 15:40:00,2019-03-23 17:52:00,5127.3,1830.3,461.46,1368.84,0.36,36.0